// app/javascript/vue/AnswerTextArea.vue
<script>
import isEmpty from 'is-empty'
import debounce from "lodash/debounce"

import * as QuestionAnswerAPI from '../api/questionAnswer'
import * as AnswerInlineImageAPI from '../api/answerInlineImage'

const isIE = navigator.userAgent.search("Trident") >= 0
const KeyCodes = {
  IMEInputting: 229,
  Enter: 13,
  Backspace: 8,
  Delete: 46
}

export default {
  props: {
    defaultValue: { type: String, default: '' },
    name: { type: String, default: 'question_answer[answer]' },
    disabled: { type: Boolean, default: false }
  },

  data: () => ({
    isIMEInputting: false,
    answers: [],
    answer: '',
    isProcessing: false,
    botId: window.currentBot.id
  }),

  created () {
    this.answer = this.defaultValue
  },

  computed: {
    isExistAnswers () {
      return this.answers.length > 0
    }
  },

  watch: {
    defaultValue () {
      this.answer = this.defaultValue
    }
  },

  methods: {
    handleTextAreaKeyDown (e) {
      this.isIMEInputting = e.keyCode === KeyCodes.IMEInputting && isIE
    },

    handleTextAreaKeyUp (e) {
      if (isIE) {
        this.handleTextAreaKeyUpForIE(e)
      } else {
        this.handleTextAreaKeyUpForModernBrowsers(e)
      }
    },

    handleTextAreaKeyUpForIE (e) {
      const isTargetKeyCode = (
        (e.keyCode === KeyCodes.Enter && this.isIMEInputting) ||
        e.keyCode === KeyCodes.Backspace || e.keyCode === KeyCodes.Delete
      )
      if (isTargetKeyCode) {
        this.isIMEInputting = false
        const { value } = e.target
        if (!isEmpty(value)) {
          this.searchAnswers(value)
        } else {
          this.answers = []
        }
      }
    },

    handleTextAreaKeyUpForModernBrowsers (e) {
      const { value } = e.target
      this.$emit('keyup', value)
      if (!isEmpty(value)) {
        this.searchAnswers(value)
      } else {
        this.answers = []
      }
    },

    searchAnswers: debounce(function(text) {
      QuestionAnswerAPI.findAll(this.botId, { q: text }).then((res) => {
        this.answers = res.data.questionAnswers
          .filter(it => it.answer !== this.answer)
          .map(it => it.answer)
      }).catch(console.error)
    }, 250),

    handleSuggestItemClick (answer) {
      this.answer = answer
      this.answers = []
    },

    handleFileInputChange (e) {
      if (this.isProcessing) { return }
      const file = e.target.files[0]
      if (file == null) { return }
      const { botId } = this
      this.isProcessing = true

      AnswerInlineImageAPI.upload({ botId, file }).then(res => {
        this.isProcessing = false
        const { url } = res.data.answerInlineImage.file
        const markdown = `\n![${file.name}](${url})\n`
        const insertPosition = this.$refs.textArea.selectionStart
        const headText = this.answer.slice(0, insertPosition)
        const tailText = this.answer.slice(insertPosition + 1)
        this.answer = headText + markdown + tailText
      }).catch(err => {
        console.error(err)
        this.isProcessing = false
      })
    }
  }
}
</script>

<template>
  <div class="form-group">
    <div class="d-flex justify-content-between align-items-center">
      <label class="mb-0">
        <i class="material-icons" title="回答">chat_bubble_outline</i>&nbsp;回答
      </label>
      <div
        class="btn btn-link file-input-container py-1"
        title="クリックして回答本文中に画像を追加できます"
      >
        <i class="material-icons">add_photo_alternate</i>
        <input
          type="file"
          class="file-input"
          @change="handleFileInputChange"
        />
      </div>
    </div>
    <textarea
      id="answer-body"
      class="form-control"
      rows="5"
      ref="textArea"
      name="question_answer[answer]"
      v-model="answer"
      :disabled="isProcessing || disabled"
      @keydown="handleTextAreaKeyDown"
      @keyup="handleTextAreaKeyUp"
    />
    <div class="card" v-if="isExistAnswers">
      <label class="m-3">回答の候補</label>
      <div
        class="suggest-item"
        v-for="(answer, i) in answers"
        :key="i"
        @click="handleSuggestItemClick(answer)"
      >
        {{answer}}
      </div>
    </div>
  </div>
</template>

<style scoped>
.form-group {
  position: relative;
}
.card {
  overflow-y: auto;
  position: absolute;
  top: calc(100% - 1px);
  left: 0;
  right: 0;
  z-index: 10;
  max-height: 200px;
  box-shadow: 0 2px 5px rgba(0,0,0,.2);
  border-radius: 0 0 0.25rem 0.25rem;
}
.suggest-item {
  cursor: pointer;
  display: block;
  padding: 16px;
  border-top: 1px solid #ccc;
  background-color: #fff;
}
.suggest-item:hover {
  background-color: #efefef;
}
.file-input-container {
  position: relative;
}
.file-input {
  display: block;
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  opacity: 0;
  width: 100%;
  height: 100%;
}
</style>

// app/assets/javascripts/es2015/components/answer-text-area.jsx
import React, { Component, PropTypes } from "react";
import debounce from "lodash/debounce";
import isEmpty from "is-empty";
import styled from 'styled-components';

import * as AnswerAPI from "../api/answer";
import Panel from "./panel";

const SuggestWrapper = styled.div.attrs({
  className: 'card'
})`
  overflow-y: auto;
  position: absolute;
  top: calc(100% - 1px);
  left: 0;
  right: 0;
  z-index: 10;
  max-height: 200px;
  box-shadow: 0 2px 5px rgba(0,0,0,.2);
  border-radius: 0 0 0.25rem 0.25rem;
`;

const SuggestItem = styled.div`
  cursor: pointer;
  display: block;
  padding: 16px;
  border-top: 1px solid #ccc;

  &:hover {
    background-color: #efefef;
  }
`;

export default class AnswerTextArea extends Component {
  static get componentName() {
    return "AnswerTextArea";
  }

  static get propTypes() {
    return {
      baseName: PropTypes.string.isRequired,
      defaultValue: PropTypes.string,
      botId: PropTypes.number.isRequired,
    };
  }

  constructor(props) {
    super(props);
    this.state = {
      text: props.defaultValue || "",
      answers: [],
    };

    this.onChangeTextArea = this.onChangeTextArea.bind(this);
    this.debouncedSearchAnswers = debounce(this.searchAnswers.bind(this), 250);
  }

  render() {
    const { baseName, botId } = this.props;
    const { text, answers } = this.state;

    return (
      <div className="form-group" style={{ position: 'relative' }}>
        <label>回答</label>
        <textArea className="form-control"
          rows={5}
          onChange={this.onChangeTextArea}
          value={text}
          name={`${baseName}[body]`}
        />
        {!isEmpty(text) && <input type="hidden" name={`${baseName}[bot_id]`} value={botId} />}
        {!isEmpty(answers) && (
          <SuggestWrapper>
            <label className="m-3">回答の候補</label>
            {answers.map((answer, i) => {
              return (
                <SuggestItem key={i} onClick={this.onClickAnswer.bind(this, answer.body)}>{answer.body}</SuggestItem>
              );
            })}
          </SuggestWrapper>
        )}
      </div>
    );
  }

  onChangeTextArea(e) {
    const { value } = e.target;
    this.setState({ text: value });
    if (!isEmpty(value)) {
      this.debouncedSearchAnswers(value);
    } else {
      this.setState({ answers: [] });
    }
  }

  onClickAnswer(text) {
    this.setState({ text, answers: [] });
  }

  searchAnswers(text) {
    const { botId } = this.props;
    AnswerAPI.findAll(botId, { q: text }).then((res) => {
      this.setState({ answers: res.data.answers });
    }).catch((err) => {
      console.error(err);
    });
  }
}
