// app/javascript/vue/Modal.vue
<template>
  <div>
    <div class="modal-backdrop fade show" />
    <div
      class="modal fade show"
      tabindex="-1"
      role="dialog"
      style="display:block"
      @click.stop.prevent="handleOutsideClick"
    >
      <div class="modal-dialog" role="document">
        <div class="modal-content">

          <div class="modal-header">
            <h5
              v-if="title"
              class="modal-title"
            >
              {{title}}
            </h5>
            <button
              type="button"
              class="close"
              aria-label="Close"
              @click.stop.prevent="handleCloseClick"
            >
              <span aria-hidden="true">&times;</span>
            </button>
          </div>

          <div class="modal-body">
            <slot name="default" />
          </div>

          <div
            v-if="$slots.footer"
            class="modal-footer"
          >
            <slot name="footer" />
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  props: {
    title: { type: String },
  },

  methods: {
    handleCloseClick () {
      this.$emit('close')
    },

    handleOutsideClick () {
      this.$emit('close')
    }
  }
}
</script>

<style>

</style>

// app/assets/javascripts/es2015/components/modal.jsx
import React, { Component } from "react";
import isEmpty from "is-empty";

export default class Modal extends Component {
  render() {
    const { onClose, title, children, iframeUrl, wide } = this.props;

    return (
      <span>
        <div className="modal-backdrop fade show" />
        <div className="modal fade show"
             style={{display:"block", overflowY:"auto"}}
             onClick={() => { onClose(); }}>
          <div className={"modal-dialog" + (wide ? " wide" : "")}
            onClick={(e) => { e.stopPropagation(); }}>
            <div className="modal-content">
              <div className="modal-header">
                <button className="close" onClick={() => { onClose(); }}>&times;</button>
                <h4 className="modal-title">{title}</h4>
              </div>
              {isEmpty(iframeUrl) && (
                <div className="modal-body">
                  {children}
                </div>
              )}
              {!isEmpty(iframeUrl) && (
                <iframe className="modal-iframe" src={iframeUrl} />
              )}
            </div>
          </div>
        </div>
      </span>
    );
  }
}
