// app/javascript/components/Modal.jsx
import React, { Component } from "react";
import classnames from 'classnames';
import isEmpty from "is-empty";

export default class Modal extends Component {
  constructor(props) {
    super(props);
    this.handleClose = this.handleClose.bind(this)
  }

  handleClose() {
    const { onClose } = this.props;
    if (typeof onClose === 'function')  {
      onClose();
    }
  }

  render() {
    const {
      onClose,
      title,
      children,
      iframeUrl,
      wide,
      narrow,
    } = this.props;

    const dialogStyle = {
      width: narrow ? '300px' : '',
    };

    return (
      <span>
        <div className="modal-backdrop fade show" />
        <div className="modal fade show"
             style={{display:"block", overflowY:"auto"}}
             onClick={this.handleClose}>
          <div
            className={classnames('modal-dialog', { wide })}
            onClick={(e) => e.stopPropagation()}
            style={dialogStyle}
          >
            <div className="modal-content">
              <div className="modal-header">
                <h4 className="modal-title">{title}</h4>
                {typeof onClose === 'function' && (
                  <button className="close" onClick={() => { onClose(); }}>&times;</button>
                )}
              </div>
              {isEmpty(iframeUrl) && (
                <div className="modal-body">
                  {children}
                </div>
              )}
              {!isEmpty(iframeUrl) && (
                <iframe className="modal-iframe" src={iframeUrl} title={title} />
              )}
            </div>
          </div>
        </div>
      </span>
    );
  }
}

// app/javascript/vue/Modal.vue
<template>
  <div>
    <div class="modal-backdrop fade show" />
    <div
      class="modal fade show"
      tabindex="-1"
      role="dialog"
      style="display:block"
      @click.stop.prevent="handleOutsideClick"
    >
      <div class="modal-dialog" role="document">
        <div class="modal-content">

          <div class="modal-header">
            <h5
              v-if="title"
              class="modal-title"
            >
              {{title}}
            </h5>
            <button
              type="button"
              class="close"
              aria-label="Close"
              @click.stop.prevent="handleCloseClick"
            >
              <span aria-hidden="true">&times;</span>
            </button>
          </div>

          <div class="modal-body">
            <slot name="default" />
          </div>

          <div
            v-if="$slots.footer"
            class="modal-footer"
          >
            <slot name="footer" />
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  props: {
    title: { type: String },
  },

  methods: {
    handleCloseClick () {
      this.$emit('close')
    },

    handleOutsideClick () {
      this.$emit('close')
    }
  }
}
</script>

<style>

</style>
