// app/javascript/vue/ConversationTree/components/AnswerNode.vue
<script>
import { mapState, mapActions } from 'vuex'
import isEmpty from 'is-empty'
import includes from 'lodash/includes'
import map from 'lodash/map'
import sortBy from 'lodash/sortBy'
import compact from 'lodash/compact'
import classnames from 'classnames'

import AnswerIcon from './AnswerIcon'
import DecisionBranchNode from './DecisionBranchNode'
import { hasChildDecisionBranch } from '../helpers'
import NodeMixin from '../mixins/Node'
import HighlightTextMixin from '../mixins/HighlightText'

export default {
  name: 'answer-node',

  mixins: [NodeMixin, HighlightTextMixin],

  props: {
    node: { type: Object, default: () => ({}) }
  },

  data: () => ({
    routeName: 'Answer'
  }),

  components: {
    AnswerIcon,
    'decision-branch-node': DecisionBranchNode
  },

  mounted () {
    this.callOpenNodeIfNeeded(this.$route)
  },

  watch: {
    $route (to, from) {
      this.callOpenNodeIfNeeded(to)
    }
  },

  computed: {
    ...mapState([
      'questionsRepo',
      'openedNodes',
      'searchingKeyword',
      'decisionBranchesRepo'
    ]),

    hasChildren () {
      return !isEmpty(this.node.decisionBranches)
    },

    nodeData () {
      return this.questionsRepo[this.node.id]
    },

    isOpened () {
      return this.isStoredOpenedNodes || this.currentPageIsChild
    }
  },

  methods: {
    ...mapActions([
      'closeNode',
      'openNode'
    ])
  }
}
</script>

<template>
  <li class="tree__node" :id="nodeId">
    <router-link
      :class="itemClassName"
      :to="`/answer/${this.node.id}`"
      @click.native="handleClick"
    >
      <span class="tree__item-body">
        <answer-icon />
        <span class="icon-circle" v-if="nodeData.answerFiles.length > 0">
          <i class="material-icons" title="添付ファイル">attachment</i>
        </span>
        <span v-html="highlight(nodeData.answer, searchingKeyword)" />
      </span>
    </router-link>
    <ol v-if="hasChildren" class="tree" :style="childTreeStyle">
      <template v-for="node in orderedDecisionBranches">
        <decision-branch-node :node="node" :key="node.id" />
      </template>
    </ol>
  </li>
</template>

// app/assets/javascripts/es2015/components/conversation-tree-app/components/answer-node.jsx
import React, { Component, PropTypes } from 'react';
import classnames from 'classnames';
import includes from 'lodash/includes';
import isEmpty from 'is-empty';

import { decisionBranchTreePropType, openedNodesType } from '../helpers';
import Tree from './tree';
import DecisionBranchNodes from './decision-branch-nodes';

class AnswerNode extends Component {
  constructor(props) {
    super(props);
    this.state = {};
    this.onClickAnswerNode = this.onClickAnswerNode.bind(this);
  }

  onClickAnswerNode(e) {
    e.stopPropagation();
    const { node, onClickAnswerNode } = this.props;
    if (isEmpty(node.decisionBranches)) { return; }
    onClickAnswerNode(node.id);
  }

  render() {
    const {
      node,
      questionsRepo,
      decisionBranchesRepo,
      openedNodes,
      onClickDecisionBranchNode,
    } = this.props;

    const { answer } = questionsRepo[node.id];
    const isOpened = includes(openedNodes.answerIds, node.id);
    const itemClassName = classnames('tree__item', {
      'tree__item--no-children': isEmpty(node.decisionBranches),
      'tree__item--opened': isOpened,
      'active': false,
    });

    return (
      <li
        className="tree__node"
        onClick={this.onClickAnswerNode}
        id={`answer-${node.id}`}
      >
        <div className={itemClassName}>
          <div className="tree__item-body">
            <i className="material-icons" title="質問">chat_bubble_outline</i>
            {answer}
          </div>
        </div>
        {!isEmpty(node.decisionBranches) && (
          <Tree isOpened={isOpened}>
            <DecisionBranchNodes
              nodes={node.decisionBranches}
              decisionBranchesRepo={decisionBranchesRepo}
              openedNodes={openedNodes}
              onClickDecisionBranchNode={onClickDecisionBranchNode}
            />
          </Tree>
        )}
      </li>
    );
  }
}

AnswerNode.propTypes = {
  node: PropTypes.shape({
    id: PropTypes.number.isRequired,
    decisionBranches: decisionBranchTreePropType,
  }),
  questionsRepo: PropTypes.object.isRequired, // FIXME より詳細に
  decisionBranchesRepo: PropTypes.object.isRequired, // FIXME より詳細に
  openedNodes: openedNodesType.isRequired,
  onClickAnswerNode: PropTypes.func.isRequired,
  onClickDecisionBranchNode: PropTypes.func.isRequired,
};

export default AnswerNode;
